"""Builds the evidence handed to the LLM for the final summary, plus a
rule-based fallback summary (no LLM) for when OPENROUTER_API_KEY is not
configured, so the product stays useful either way."""

from __future__ import annotations

from app.llm.types import EvidenceItem
from app.models.models import Article, ArticleRelation

ROLE_BY_RELATION = {
    "confirmation": "confirms",
    "developing": "unconfirmed development",
    "correction": "corrects",
    "reaction": "reacts",
    "update": "updates",
    "republication": "republishes",
    "cites": "cites",
    "same_story": "same story",
}


def build_evidence(
    articles: list[Article], relations: list[ArticleRelation], claims_by_article: dict[str, list[str]]
) -> list[EvidenceItem]:
    role_by_article: dict[str, str] = {}
    for rel in relations:
        role_by_article[rel.target_article_id] = ROLE_BY_RELATION.get(rel.relation.value, "related")

    items: list[EvidenceItem] = []
    for article in sorted(articles, key=lambda a: a.published_at or a.created_at):
        role = "origin" if article.is_origin else role_by_article.get(article.id, "related")
        items.append(
            EvidenceItem(
                source=f"{article.domain}" + (f" ({article.source_handle})" if article.source_handle else ""),
                published_at=article.published_at.isoformat() if article.published_at else None,
                headline=article.title or article.url,
                role=role,
                claims=claims_by_article.get(article.id, [])[:2],
            )
        )
    return items


def rule_based_summary(
    articles: list[Article],
    relations: list[ArticleRelation],
    divergence_count: int,
    llm_configured: bool = False,
) -> str:
    """Simple extractive summary, without an LLM, used when no API key is
    configured (VeriGraph.md: the summary must still be produced, only
    without the semantic depth of the LLM)."""
    if not articles:
        return "Not enough sources were found to reconstruct this story."

    ordered = sorted(articles, key=lambda a: a.published_at or a.created_at)
    origin = next((a for a in ordered if a.is_origin), ordered[0])
    pub = origin.published_at
    # Many sources only provide the date; the parser fills the missing time
    # with midnight UTC, which is not a real clock time.
    has_time = pub and not (pub.hour == 0 and pub.minute == 0 and pub.second == 0)
    origin_time = pub.strftime("%H:%M") if has_time else "unknown time"

    parts = [
        f"{len(articles)} publications related to this story were found.",
        f'The earliest version located was "{origin.title or origin.url}" '
        f"({origin.domain}, {origin_time}).",
    ]

    correction_edges = [r for r in relations if r.relation.value == "correction"]
    if correction_edges:
        parts.append(
            f"{len(correction_edges)} formal corrections to earlier versions were detected."
        )
    if divergence_count:
        parts.append(
            f"The system identified {divergence_count} divergence(s) between the claims of "
            "different sources; inspect each node for the details."
        )
    else:
        parts.append("No clear contradictions were identified between the analysed sources.")

    if llm_configured:
        parts.append(
            "The semantic summary could not be generated with the language model on this attempt "
            "(the service did not respond); this is a basic summary produced without an LLM."
        )
    else:
        parts.append(
            "Set your OPENROUTER_API_KEY in the .env file to get a more detailed semantic summary "
            "generated by the language model."
        )
    return " ".join(parts)
